---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: domoticz-mqtt-broker-claim
spec:
  storageClassName: microk8s-hostpath
  accessModes:
    - ReadWriteMany
  volumeMode: Filesystem
  resources:
    requests:
      storage: 10Mi
