---
apiVersion: v1
kind: Service
metadata:
  name: domoticz-mqtt-broker
spec:
  type: ClusterIP
  ports:
    - name: unencrypted
      port: 1883
      targetPort: 1883
      protocol: TCP
    - name: websockets
      port: 9001
      targetPort: 9001
      protocol: TCP
  selector:
    app: domoticz-mqtt-broker


